version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  audio-storage:
    build:
      context: .
      dockerfile: Dockerfile
    image: audio-storage
    depends_on:
      - minio
    volumes:
      - .:/app
    entrypoint: ["/audio-storage"]
    environment:
      - ENV=development
      - CHUNK_SIZE=5242880 # 5MB
      - TEMP_DIR=./temp
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=audio-files

volumes:
  minio_data:
    driver: local
